from __future__ import annotations

TEXT = {
    "tr": {
        "brand_tag": "Yazilim, otomasyon ve dijital sistemler.",
        "nav_home": "Ana Sayfa",
        "nav_about": "Hakkimizda",
        "nav_services": "Hizmetler",
        "nav_work": "Projeler",
        "nav_contact": "Iletisim",
        "nav_login": "Giris Yap",
        "nav_register": "Kayit Ol",
        "nav_dashboard": "Panel",
        "nav_admin": "Admin",
        "nav_logout": "Cikis",
        "home_title": "Modern sirketler icin guven veren yazilim platformlari kuruyoruz.",
        "home_text": "Asil Forge; kurumsal web platformlari, musteri portallari, otomasyon altyapilari ve dijital cozumler gelistiren premium bir yazilim sirketi deneyimi sunar.",
        "cta_primary": "Proje Baslat",
        "cta_secondary": "Hizmetleri Incele",
        "section_capabilities": "Yetenekler",
        "section_process": "Surec",
        "section_showcase": "Secili Isler",
        "section_insights": "Yazilar",
        "section_contact": "Iletisime Gec",
        "stats_title": "Platform Genel Bakis",
        "stat_users": "Kullanicilar",
        "stat_projects": "Projeler",
        "stat_messages": "Mesajlar",
        "services_title": "Yalnizca gorunen degil, gercekten calisan yazilim sistemleri.",
        "about_title": "Asil Forge, sirketlerin dijital omurgasini kurar.",
        "about_text": "Marka sunumundan proje takibine kadar tum akisi tek bir profesyonel urun deneyimi icinde birlestiririz.",
        "contact_title": "Projeni ve ihtiyacini paylas, sana sistemli donelim.",
        "contact_text": "Iletisim formu ve proje talep sistemi ayni veri akisi uzerinden duzenli bir takip surecine duser.",
        "login_title": "Hesabina guvenli sekilde giris yap.",
        "register_title": "Asil Forge platformunda hesabini olustur.",
        "forgot_title": "Sifre sifirlama baglantisi iste.",
        "reset_title": "Yeni sifreni belirle.",
        "verify_title": "E-posta dogrulama",
        "dashboard_title": "Musteri Paneli",
        "dashboard_text": "Proje taleplerini, hesap ayarlarini ve gecmis hareketlerini yonet.",
        "admin_title": "Admin Kontrol Merkezi",
        "admin_text": "Kullanicilar, proje talepleri, mesajlar ve bildirim kuyrugu tek panelde.",
        "field_name": "Ad Soyad",
        "field_email": "E-posta",
        "field_password": "Sifre",
        "field_password_confirm": "Sifre Tekrari",
        "field_subject": "Konu",
        "field_message": "Mesaj",
        "field_project_title": "Proje Basligi",
        "field_description": "Aciklama",
        "field_budget": "Butce",
        "field_deadline": "Teslim Tarihi",
        "field_locale": "Dil",
        "field_notes": "Admin Notu",
        "field_status": "Durum",
        "field_role": "Rol",
        "field_captcha": "Guvenlik Sorusu",
        "field_robot": "Ben robot degilim",
        "btn_send": "Gonder",
        "btn_save": "Kaydet",
        "btn_update": "Guncelle",
        "btn_delete": "Sil",
        "btn_login": "Giris Yap",
        "btn_register": "Kayit Ol",
        "btn_reset": "Sifreyi Yenile",
        "btn_request": "Proje Talebi Gonder",
        "btn_reply": "Yanitla",
        "btn_change_password": "Sifreyi Degistir",
        "btn_mark_done": "Tamamlandi Yap",
        "status_pending": "Beklemede",
        "status_in_progress": "Devam Ediyor",
        "status_completed": "Tamamlandi",
        "status_rejected": "Reddedildi",
        "status_new": "Yeni",
        "status_replied": "Yanitlandi",
        "status_verified": "Dogrulandi",
        "status_unverified": "Dogrulanmadi",
        "hero_point_1": "Kurumsal web siteleri",
        "hero_point_2": "Musteri portallari ve is panelleri",
        "hero_point_3": "Otomasyon ve is akis sistemleri",
        "process_1_title": "Kesif",
        "process_1_text": "Ihtiyaci dinler, is akisini cikarir ve sistem sinirlarini netlestiririz.",
        "process_2_title": "Tasarim ve Mimari",
        "process_2_text": "Public site, kullanici paneli ve is akisi ekranlarini ayri ama uyumlu kurgulariz.",
        "process_3_title": "Gelistirme ve Takip",
        "process_3_text": "Talep, durum, bildirim ve raporlama akisini gercek bir urun gibi kurariz.",
        "showcase_tag": "Gercek urun mantigi",
        "form_required": "Lutfen gerekli alanlari doldur.",
        "form_invalid_email": "Gecerli bir e-posta gir.",
        "form_password_match": "Sifreler eslesmiyor.",
        "form_robot": "Guvenlik dogrulamasini tamamla.",
        "flash_register_success": "Kayit tamamlandi. Dogrulama e-postasi kuyruga alindi.",
        "flash_login_success": "Giris basarili.",
        "flash_logout_success": "Oturum kapatildi.",
        "flash_invalid_login": "E-posta veya sifre hatali.",
        "flash_contact_success": "Mesajin basariyla alindi.",
        "flash_project_success": "Proje talebin alindi.",
        "flash_profile_saved": "Profil bilgileri guncellendi.",
        "flash_password_changed": "Sifren guncellendi.",
        "flash_reset_sent": "Sifre sifirlama baglantisi kuyruga alindi.",
        "flash_reset_success": "Sifren yenilendi, simdi giris yapabilirsin.",
        "flash_verify_success": "E-posta dogrulamasi tamamlandi.",
        "flash_admin_saved": "Yonetim islemi kaydedildi.",
        "flash_rate_limited": "Cok fazla istek gonderdin. Lutfen biraz bekle.",
        "flash_forbidden": "Bu alana erisim iznin yok.",
        "flash_captcha_invalid": "Guvenlik sorusuna dogru cevap ver.",
        "flash_inactive_user": "Bu hesap pasif durumda.",
        "flash_email_exists": "Bu e-posta zaten kayitli.",
        "flash_verification_needed": "E-posta dogrulamasi tavsiye edilir.",
        "table_users": "Kullanicilar",
        "table_projects": "Projeler",
        "table_messages": "Mesajlar",
        "table_notifications": "Bildirimler",
        "table_activity": "Aktivite",
        "footer_copy": "Asil Forge - premium yazilim platformlari.",
        "project_empty": "Henuz proje bulunmuyor.",
        "message_empty": "Henuz mesaj bulunmuyor.",
        "activity_empty": "Aktivite kaydi bulunmuyor.",
        "outbox_note": "Yerel ortamda e-postalar bildirim kuyruğuna kaydedilir.",
        "profile_section": "Profil ve Ayarlar",
        "security_section": "Guvenlik",
        "request_section": "Proje Talep Formu",
    },
    "en": {
        "brand_tag": "Software, automation, and digital systems.",
        "nav_home": "Home",
        "nav_about": "About",
        "nav_services": "Services",
        "nav_work": "Projects",
        "nav_contact": "Contact",
        "nav_login": "Login",
        "nav_register": "Register",
        "nav_dashboard": "Dashboard",
        "nav_admin": "Admin",
        "nav_logout": "Logout",
        "home_title": "We build trusted software platforms for modern companies.",
        "home_text": "Asil Forge delivers a premium software company experience across corporate websites, client portals, automation infrastructure, and digital solutions.",
        "cta_primary": "Start a Project",
        "cta_secondary": "Explore Services",
        "section_capabilities": "Capabilities",
        "section_process": "Process",
        "section_showcase": "Selected Work",
        "section_insights": "Insights",
        "section_contact": "Contact",
        "stats_title": "Platform Overview",
        "stat_users": "Users",
        "stat_projects": "Projects",
        "stat_messages": "Messages",
        "services_title": "Not just attractive interfaces, but real software systems that work.",
        "about_title": "Asil Forge builds the digital backbone of modern companies.",
        "about_text": "We unify brand presence, client operations, workflow systems, and project delivery into one consistent product experience.",
        "contact_title": "Share your project and we will respond with a structured plan.",
        "contact_text": "The contact form and project request flow are designed to move into a structured delivery process.",
        "login_title": "Sign in to your account securely.",
        "register_title": "Create your Asil Forge platform account.",
        "forgot_title": "Request a password reset link.",
        "reset_title": "Set your new password.",
        "verify_title": "Email verification",
        "dashboard_title": "Client Dashboard",
        "dashboard_text": "Manage project requests, account settings, and activity history.",
        "admin_title": "Admin Control Center",
        "admin_text": "Users, projects, messages, and notification queue in one panel.",
        "field_name": "Full Name",
        "field_email": "Email",
        "field_password": "Password",
        "field_password_confirm": "Confirm Password",
        "field_subject": "Subject",
        "field_message": "Message",
        "field_project_title": "Project Title",
        "field_description": "Description",
        "field_budget": "Budget",
        "field_deadline": "Deadline",
        "field_locale": "Language",
        "field_notes": "Admin Note",
        "field_status": "Status",
        "field_role": "Role",
        "field_captcha": "Security Check",
        "field_robot": "I am not a robot",
        "btn_send": "Send",
        "btn_save": "Save",
        "btn_update": "Update",
        "btn_delete": "Delete",
        "btn_login": "Login",
        "btn_register": "Register",
        "btn_reset": "Reset Password",
        "btn_request": "Submit Project Request",
        "btn_reply": "Reply",
        "btn_change_password": "Change Password",
        "btn_mark_done": "Mark Completed",
        "status_pending": "Pending",
        "status_in_progress": "In Progress",
        "status_completed": "Completed",
        "status_rejected": "Rejected",
        "status_new": "New",
        "status_replied": "Replied",
        "status_verified": "Verified",
        "status_unverified": "Unverified",
        "hero_point_1": "Corporate web platforms",
        "hero_point_2": "Client portals and work panels",
        "hero_point_3": "Automation and workflow systems",
        "process_1_title": "Discovery",
        "process_1_text": "We map the need, define the flow, and clarify system boundaries.",
        "process_2_title": "Architecture",
        "process_2_text": "We separate the public site, user dashboard, and workflow screens into a clean system.",
        "process_3_title": "Delivery",
        "process_3_text": "We build requests, statuses, notifications, and reporting as a real product.",
        "showcase_tag": "Real product thinking",
        "form_required": "Please fill in the required fields.",
        "form_invalid_email": "Enter a valid email address.",
        "form_password_match": "Passwords do not match.",
        "form_robot": "Complete the security confirmation.",
        "flash_register_success": "Registration completed. Verification email has been queued.",
        "flash_login_success": "Login successful.",
        "flash_logout_success": "You have been signed out.",
        "flash_invalid_login": "Incorrect email or password.",
        "flash_contact_success": "Your message has been received.",
        "flash_project_success": "Your project request has been submitted.",
        "flash_profile_saved": "Profile details updated.",
        "flash_password_changed": "Password updated.",
        "flash_reset_sent": "Password reset link has been queued.",
        "flash_reset_success": "Password reset successful. You can now log in.",
        "flash_verify_success": "Email verification completed.",
        "flash_admin_saved": "Admin update saved.",
        "flash_rate_limited": "Too many requests. Please wait a moment.",
        "flash_forbidden": "You do not have access to this area.",
        "flash_captcha_invalid": "Answer the security challenge correctly.",
        "flash_inactive_user": "This account is inactive.",
        "flash_email_exists": "That email is already registered.",
        "flash_verification_needed": "Email verification is recommended.",
        "table_users": "Users",
        "table_projects": "Projects",
        "table_messages": "Messages",
        "table_notifications": "Notifications",
        "table_activity": "Activity",
        "footer_copy": "Asil Forge - premium software platforms.",
        "project_empty": "No projects yet.",
        "message_empty": "No messages yet.",
        "activity_empty": "No activity records yet.",
        "outbox_note": "Emails are stored in the notification queue in local development.",
        "profile_section": "Profile & Settings",
        "security_section": "Security",
        "request_section": "Project Request Form",
    },
}

SERVICES = [
    {
        "title": {"tr": "Kurumsal Web Platformlari", "en": "Corporate Web Platforms"},
        "text": {
            "tr": "Sadece landing page degil, guven veren ve teklif toplayan sirket siteleri.",
            "en": "Not just landing pages, but company sites that build trust and convert opportunities.",
        },
    },
    {
        "title": {"tr": "Musteri Portallari ve Is Panelleri", "en": "Client Portals & Work Panels"},
        "text": {
            "tr": "Rol bazli erisim, durum takibi, panel akislar ve operasyon ekranlari.",
            "en": "Role-based access, status tracking, operational views, and internal tools.",
        },
    },
    {
        "title": {"tr": "Otomasyon Sistemleri", "en": "Automation Systems"},
        "text": {
            "tr": "Bildirim, veri akisi, rutin isler ve raporlama icin akilli surecler.",
            "en": "Smart flows for notifications, data movement, repeatable work, and reporting.",
        },
    },
]

SHOWCASE_ITEMS = [
    {
        "title": {"tr": "Asil Ofisi", "en": "Asil Office"},
        "text": {
            "tr": "Musteri taleplerini, dahili operasyonu ve yonetim akislarini tek premium arayuzde birlestiren dijital ofis platformu.",
            "en": "A digital office platform that unifies client requests, internal operations, and management flows inside one premium interface.",
        },
    },
    {
        "title": {"tr": "ClientOps Workspace", "en": "ClientOps Workspace"},
        "text": {
            "tr": "Musteri taleplerini, belgeleri ve durum guncellemelerini tek panelde toplayan sistem.",
            "en": "A workspace that centralizes client requests, files, and status updates in one place.",
        },
    },
    {
        "title": {"tr": "Forge Control Suite", "en": "Forge Control Suite"},
        "text": {
            "tr": "Proje talepleri, mesajlar ve teslim sureclerini tek merkezde toplayan kontrol deneyimi.",
            "en": "A control experience that centralizes project requests, messages, and delivery workflows.",
        },
    },
    {
        "title": {"tr": "Automation Relay", "en": "Automation Relay"},
        "text": {
            "tr": "Formlar, durum degisiklikleri ve e-posta kuyrugunu birbirine baglayan arka plan akisi.",
            "en": "A background flow connecting forms, status updates, and notification delivery.",
        },
    },
]

BLOG_SEED = [
    {
        "slug": "building-client-portals-that-scale",
        "title": "Building Client Portals That Scale",
        "excerpt": "How a software company website becomes a working service platform instead of a static brochure.",
        "body": "A strong software company platform separates public trust-building pages from operational dashboards. The public site sells confidence, while the dashboard manages delivery, project updates, and client communication.",
    },
    {
        "slug": "why-delivery-systems-shape-growth",
        "title": "Why Delivery Systems Shape Growth",
        "excerpt": "Structured delivery systems make response time, quality, and client trust visible in daily operations.",
        "body": "A delivery system is not an afterthought. When project requests, messages, and notifications live in one place, the company behaves more like a product organization and less like a collection of disconnected tasks.",
    },
]


def t(lang: str, key: str) -> str:
    return TEXT.get(lang, TEXT["en"]).get(key, TEXT["en"].get(key, key))
